### ISSUE TITLE
Error after pip install | ModuleNotFoundError: No module named 'markupsafe'

### ISSUE THREAD

**Issue by rvernica** [sphinx-toolbox/sphinx-jinja2-compat#2]
## Description

Python setup broken after `pip install sphinx_jinja2_compat`

## Steps to Reproduce

   1. `pip install sphinx_jinja2_compat`
   2. `python`

## Actual result:

```
> pip install sphinx_jinja2_compat
Defaulting to user installation because normal site-packages is not writeable
Collecting sphinx_jinja2_compat
  Using cached sphinx_jinja2_compat-0.1.2-py3-none-any.whl (12 kB)
Requirement already satisfied: markupsafe>=1 in /usr/lib64/python3.10/site-packages (from sphinx_jinja2_compat) (2.0.0)
Requirement already satisfied: jinja2>=2.10 in /usr/lib/python3.10/site-packages (from sphinx_jinja2_compat) (3.0.1)
Installing collected packages: sphinx-jinja2-compat
Successfully installed sphinx-jinja2-compat-0.1.2

> python
Error processing line 1 of /home/foo/.local/lib/python3.10/site-packages/_sphinx_jinja2_compat.pth:

  Traceback (most recent call last):
    File "/usr/lib64/python3.10/site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "/home/foo/.local/lib/python3.10/site-packages/sphinx_jinja2_compat/__init__.py", line 44, in <module>
      import markupsafe  # noqa: E402
  ModuleNotFoundError: No module named 'markupsafe'

Remainder of file ignored
Python 3.10.4 (main, Mar 25 2022, 00:00:00) [GCC 11.2.1 20220127 (Red Hat 11.2.1-9)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import markupsafe
>>> markupsafe.__version__
'2.0.0'
```

## Reproduces how often:

I tried all available versions of the package `0.1.0`-`0.1.2`

## Version

  * Operating System:  Fedora `35`
  * Python: `3.10`
  * sphinx-jinja2-compat: `0.1.0`-`0.1.2`

## Installation source

PyPI

## Other Additional Information:

Don't really need the package, it just came up with the `sphinx-toolbox` package.

**Comment by domdfcoding** [comment]
I think I see the issue. You have jinja2 and markupsafe installed in `/usr/lib64/python3.10/site-packages` (presumably by yum) but sphinx-jinja2-compat in `/home/foo/.local/lib/python3.10/site-packages/`. It looks like `/usr/lib64/python3.10/site-packages` isn't yet on the Python path when `sphinx-jinja2-compat` tries to do its thing, hence the error. 

I have implemented a workaround in version 0.2.0b1. Can you try with that version? (`pip install sphinx-jinja2-compat==0.2.0b1`)

**Comment by rvernica** [comment]
This seems to work. It produces some printout which I guess is for debugging:
```
> pip install sphinx-jinja2-compat==0.2.0b1
...
Successfully installed sphinx-jinja2-compat-0.2.0b1

> python
abrt_exception_handler3
sitecustomize
usercustomize
Python 3.10.4 (main, Mar 25 2022, 00:00:00) [GCC 11.2.1 20220127 (Red Hat 11.2.1-9)] on linux
Type "help", "copyright", "credits" or "license" for more information.
readline
atexit
rlcompleter
inspect
ast
_ast
dis
opcode
_opcode
linecache
tokenize
token
>>> 
```

**Comment by MatthewFlamm** [comment]
I also had this problem.  While upgrading to 0.2.0b1 removes the error, I also get the print statements.  Is there a method to turn those off?
